// Auto-generated by make — do not edit
let buildVersion = "0.1.1"
let buildCommit = "ba8cccd"
let buildBranch = "main"
let buildDate = "2026-04-03 23:10:37 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
