// Auto-generated by make — do not edit
let buildVersion = "dev"
let buildCommit = "unknown"
let buildBranch = "unknown"
let buildDate = "unknown"
let buildSwiftVersion = "unknown"
let buildOS = "unknown"
